#Logger
logging:
  level:
    com.promotick: DEBUG
    com.promotick.lafabril.dao: INFO
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource: DEBUG
#Promotick
promotick:
  web:
    helper: false
    thymeleaf:
      enabled: true
      admin: false
  logger: true

#Server
server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: LaFabrilWeb
  jmx:
    default-domain: LaFabrilWeb
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
    