#Promotick
promotick:
  web:
    mvc:
      resource:
        root: http://localhost:8080/Resources
#        root: https://4b73-190-43-118-96.sa.ngrok.io/Resources
        admin: public/admin
        web: public/web
        recompensa: public/recompensa
        common: public/common
        template: public/web/plantillas
      context:
        root: http://localhost:8080
        web: MemberShipWeb
        recompensa: Recompensas
    thymeleaf:
      webTemplates: C:\Users\hp\Desktop\Stephanie\Trabajos\Promotick\WrksJava\membership-misiones-ec\Libraries\src\main\resources\templatesWeb

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
