#Recopemsas JWT Configuration
recompensas:
  configuration:
    url_base_token: https://identity.dev.bancoguayaquil.com
    url: https://premios.membershiprewards.com.ec
    grant_type: client_credentials
    client_id: 4276a3c9
    client_secret: qJJROEhih0vVZGwEWFGpGputxVL1a8b6
    host:

