#Pasarela
pasarela:
  configuration:
    key: LpZJiL6hu0G2gJu8pTz1cqDAxctNyM
    currency: USD
    code: PROM-EC
    conversion: 0.02
    mode: stg


#ApiMassend
massend:
  configuration:
    url: https://api.massend.com/api/sms
    user: promotick@massend.com
    pass: Promo$2022
    rutaInformativo: 0
    rutaMarketing: 1
    tipofijo: 0
    tipovariable: 1
    mensajeidBienvenida: 26406
    mensajeidPuntos: 26403
    mensajeidCanje: 26404