#Promotick
promotick:
  web:
    mvc:
      resource:
        root: http://localhost:8080/Resources
#        root: https://4b73-190-43-118-96.sa.ngrok.io/Resources
        admin: public/admin
        web: public/web
        recompensa: public/recompensa
        common: public/common
        template: public/web/plantillas
        mail: G:\workspace-promotick\lafabril-ec\Resources\WebContent\public\web\mail
      context:
        root: http://localhost:8080
        web: LaFabrilWeb
        admin: LaFabrilAdmin
        recompensa: Recompensas
    thymeleaf:
      adminTemplates: /Users/karlrenzo/Desktop/Proyectos/lafabril-ec/Libraries/src/main/resources/templatesAdmin
      webTemplates: C:\Users\ENRIQUE\Desktop\trabajo\membership-misiones-ec\Libraries\src\main\resources\templatesWeb
  api:
    client:
      autenticated: true
      logger: true
      dirTemporal: /Users/karlrenzo/Desktop/Proyectos
      programID: 18
      url: http://recursos.promotick.com.pe/framework-api-server-tomcat
      username: api-server-promotick
      password: hkIUtJmnq5sda
      netsuite:
        url: http://10.0.0.249:8080/cron
        register: RegistrarPedidoEcuador
        enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

nissan:
  sms:
    campania:
      bienvenida: 1
      cargapuntos: 4
      canjes: 7
